
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta name="apple-mobile-web-app-capable" content="yes">

	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
	<meta name="description" content="">
	<meta name="author" content="">
	<link rel="icon" href="../../favicon.ico">

	<title>TBook - Find Your Friends</title>

	<!-- Bootstrap core CSS -->
	<link rel="stylesheet" href="/assets/css.min.css">
	<script src="/assets/js.min.js"></script>


	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

<!--	<script src="https://use.fontawesome.com/491ec1b91a.js"></script>-->
</head>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/">TBook - Find Your Friends</a>
		</div>
		<div id="navbar" class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li class=""><a href="/">My Feed</a></li>
				<li class=""><a href="/user/profile/<?php echo Session::GetUsername(); ?>">Me</a></li>
				<li class=""><a href="/user/groups/<?php echo Session::GetUsername(); ?>">My Groups</a></li>
				<li class="">
					<a href="/chat">
						Chat
					</a>
				</li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<?php
					if(!Authentication::isLoggedIn()) {
						?>
						<li class="pull-right">
							<a href="/account/register">Register</a>
						</li>
						<li class="pull-right">
							<a href="/account/login">Login</a>
						</li>
						<?php
					} else {
						?>
						<li class="dropdown pull-right">
							<a href="/account" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?php echo Session::GetUsername(); ?></a>
							<ul class="dropdown-menu">
								<li><a href="/account/settings"><i class="fa fa-gear"></i> Settings</a></li>
								<li><a href="/account/history"><i class="fa fa-clock-o"></i> History</a> </li>
								<li><a href="/account/logout"><i class="fa fa-lock"></i> Log out</a> </li>
							</ul>
						</li>
						<?php
					}
				?>
			</ul>
		</div><!--/.nav-collapse -->
	</div>
</nav>


<div class="row intro-row">
	<div class="col col-sm-12 vertical-center">
		<h2 class="text-center">Welcome, <?php echo explode(" ", Profile::GetLoggedIn()->name)[0]; ?></h2>
		<h5 class="text-center">Scroll down to see what's happening</h5>
	</div>
</div>

<div class="container" id="mPHP-Content">
</div><!-- /.container -->



<footer class="footer">
	<div class="container">
		<h1>TBook - Find Your Friends</h1>
		<p>
			<a class="footer-link" href="/">My Feed</a>
			<a class="footer-link" href="/user/profile/<?php echo Session::GetUsername(); ?>">My Profile</a>
			<a class="footer-link" href="/user/groups/<?php echo Session::GetUsername(); ?>">My Groups</a>
			<a class="footer-link" href="/chat">Chat</a>
			<a class="footer-link" href="/account/logout">Log Out</a>
		</p>
		<div class="row">
			<div class="col col-sm-4">
				<h3>Try Something New:</h3>
				<a class="footer-new" href="/chat">Make a group chat</a>
				<a class="footer-new" href="/group/find">Join a group</a>
				<a class="footer-new" href="/group/create">Create a group</a>
				<a class="footer-new" href="/photos/create">Create an album</a>
			</div>
		</div>
		<div class="row">
			<div class="col col-sm-12 pull-bottom">
				<p>
					&copy; <?php echo date("Y"); ?> Saga Systems | Based on the <a style="color:white;" href="https://github.com/mvinc17/mPHP" target="_blank">mPHP MVC Framework</a> | Powered by PHP7 | Rendered in <?php global $startTime; echo round((microtime(true) - $startTime) * 1000, 2); ?> ms
				</p>
			</div>
		</div>
	</div>
</footer>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
</body>
</html>
