<style>
	.intro-row {
		display: block;
		margin-top:-50px;
	}
	nav:not(.scrolled) {
		background-color: transparent;
		border-color: transparent;
	}
	nav:not(.scrolled) .navbar-nav>li>a:hover, .navbar-inverse .navbar-nav>li>a:focus {
		background-color: transparent;
	}
</style>
<script>
	$(window).scroll(function() {
		if(window.scrollY > 250) {
			$("nav").addClass("scrolled");
		} else {
			$("nav").removeClass("scrolled");
		}
	});
</script>
<section class="main">
	<div class="row">
		<div class="col col-md-8">
			<div class="well clearfix">
				<h3>Post an Update</h3>
				<form class="new-post-form" action="#" method="POST" enctype="multipart/form-data">
					<div class="form-group">
						<textarea class="form-control" name="content" placeholder="What's on your mind..."></textarea>
					</div>
					<div class="form-group">
						<input type="text" name="tagged" class="form-control" style="width:100%;" data-role="tagsinput" id="tagged-in" placeholder="Who were you with?">
					</div>
					<div class="form-group pull-left">
						Upload a Photo<input name="post-image" type="file" class="new-post-file-input">
					</div>
					<input type="submit" class="btn btn-success pull-right" value="Post">
				</form>
			</div>
		</div>
		<div class="col col-md-4">
			<div class="well clearfix new-things">
				<h3>Try Something New</h3>
				<a href="/chat">Start a group chat</a>
				<a href="/group/find">Join a group</a>
				<a href="/"></a>
			</div>
		</div>
	</div>
	<div class="row">
		<?php
		$i = 0;
		$n = 0;
		foreach(Posts::GetPosts(true) as $post) {
			if($n > 2) {
				?>
					</div>
					<div class="row">
				<?php
				$n = 0;
			}
			$n++;
			if($i > 8) {
				$i = 0;
				?>
				<a class="col col-xs-12 feed-ad" style="display:block;background-image: url(/assets/img/rmit.jpg);" href="https://www.rmit.edu.au/" target="_blank">
				</a>
				<?php
			} else {
				$i++;
			}
			control("DisplayPost", $post);
		}
		?>
	</div>
</section>