<div class="row">
	<div class="col col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12 box-shadow">
		<h3 class="text-center">Sign Up to TBook</h3>
		<form action="#" method="POST" id="signup-form">
			<div class="form-group">
				<input type="text" class="form-control" placeholder="Full Name" name="name">
			</div>
			<div class="form-group">
				<input type="text" class="form-control" placeholder="Username" name="username" id="username">
			</div>
			<div class="form-group">
				<input type="password" class="form-control" placeholder="Password" name="password">
			</div>
			<div class="form-group">
				<textarea name="bio" placeholder="About You" class="form-control"></textarea>
			</div>
			<div class="form-group">
				<label>Profile Picture</label>
				<input name="profile-pic" type="file">
			</div>
			<div class="form-group">
				<label>Cover Photo</label>
				<input name="cover-pic" type="file">
			</div>
			<input type="submit" class="btn btn-block btn-success" value="Sign Up">
		</form>
	</div>
</div>
<script>
	$("form").submit(function(e) {
		e.preventDefault();
		$(this).find("input.btn[type=submit]").val('Please Wait').prop("disabled", true);
		//var formData = new FormData(this);
		$.ajax({
			url: '/ajax/sign_up',
			method: 'POST',
			data: new FormData( this ),
			processData: false,
			contentType: false,
			success: function() {
				window.location.href = '/user/profile/' + $("#username").val();
			}
		});
	});
</script>